/*
389. Find the Difference
You are given two strings s and t.
String t is generated by random shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.

Example 1: Input: s = "abcd", t = "abcde" Output: "e"
Example 2: Input: s = "", t = "y" Output: "y"

Constraints:0 <= s.length <= 1000 || t.length == s.length + 1
s and t consist of lowercase English letters.

Difficulty: Easy

Time Complexity: O(n) where n is the length of string t.
Space Complexity: O(1) since we are using a constant amount of space to store the result.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        
        char result = 0;

        for(char c  : s.toCharArray()){
            result ^= c;
        }
        for(char c : t.toCharArray()){
            result ^= c;
        }
        return result;
    }
}